-- Migration 005: Core Attendance Tables
-- attendance_session, attendance_session_student, attendance_record

CREATE TABLE IF NOT EXISTS attendance_session (
  session_id           TEXT PRIMARY KEY,  -- UUID generated by application
  institution_id       TEXT NOT NULL REFERENCES institution(id),
  faculty_id           TEXT NOT NULL REFERENCES faculty(faculty_id),
  subject_id           TEXT NOT NULL REFERENCES subject(subject_id),
  batch_id             TEXT NOT NULL REFERENCES batch(batch_id),
  academic_year_id     TEXT NOT NULL REFERENCES academic_year(academic_year_id),
  semester_id          TEXT REFERENCES semester(semester_id),
  section_id           TEXT REFERENCES section(section_id),
  student_group_id     TEXT REFERENCES student_group(student_group_id),
  topic_id             TEXT REFERENCES topic(topic_id),
  topic_notes          TEXT,
  session_date         TEXT NOT NULL,
  start_time           TEXT NOT NULL,
  end_time             TEXT,              -- Set at submission
  duration_minutes     INTEGER,           -- Calculated and stored at submission
  device_id            TEXT,
  location             TEXT,
  status               TEXT NOT NULL DEFAULT 'DRAFT'
                       CHECK(status IN (
                         'DRAFT','OPEN','SUBMITTED','LOCKED',
                         'SYNC_PENDING','SYNCED','CANCELLED','VOIDED','SYNC_CONFLICT'
                       )),
  source               TEXT NOT NULL DEFAULT 'DESKTOP'
                       CHECK(source IN ('MOBILE','DESKTOP','IMPORT')),
  counted_for_workload INTEGER NOT NULL DEFAULT 1,
  submitted_at         TEXT,
  submitted_by         TEXT,
  sync_status          TEXT NOT NULL DEFAULT 'NOT_REQUIRED'
                       CHECK(sync_status IN (
                         'NOT_REQUIRED','PENDING','UPLOADING','SYNCED','FAILED','CONFLICT'
                       )),
  version              INTEGER NOT NULL DEFAULT 1,
  created_at           TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at           TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Partial unique index: prevent duplicate OPEN sessions for same faculty/subject/batch/date
CREATE UNIQUE INDEX IF NOT EXISTS uq_open_faculty_session
  ON attendance_session(institution_id, faculty_id, subject_id, batch_id, session_date)
  WHERE status = 'OPEN';

CREATE INDEX IF NOT EXISTS idx_session_date
  ON attendance_session(institution_id, session_date, status);

CREATE INDEX IF NOT EXISTS idx_session_faculty
  ON attendance_session(faculty_id, status, session_date);

CREATE INDEX IF NOT EXISTS idx_session_subject
  ON attendance_session(subject_id, batch_id, session_date);

-- Workload query index
CREATE INDEX IF NOT EXISTS idx_session_workload
  ON attendance_session(faculty_id, status, counted_for_workload, session_date);

-- Eligible student snapshot: frozen at session OPEN time
CREATE TABLE IF NOT EXISTS attendance_session_student (
  session_student_id   TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  institution_id       TEXT NOT NULL REFERENCES institution(id),
  session_id           TEXT NOT NULL REFERENCES attendance_session(session_id) ON DELETE CASCADE,
  student_id           TEXT NOT NULL REFERENCES student(student_id),
  eligibility_source   TEXT NOT NULL
                       CHECK(eligibility_source IN ('SUBJECT_ENROLLMENT','GROUP_MEMBERSHIP','MANUAL')),
  subject_enrollment_id  TEXT REFERENCES student_subject_enrollment(enrollment_id),
  group_membership_id  TEXT REFERENCES student_group_membership(membership_id),
  eligible_at          TEXT NOT NULL DEFAULT (datetime('now')),
  created_at           TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(session_id, student_id)  -- A student appears only once per session
);

CREATE INDEX IF NOT EXISTS idx_session_student_lookup
  ON attendance_session_student(session_id, student_id);

-- Attendance record: one row per eligible student per session, pre-created as ABSENT
CREATE TABLE IF NOT EXISTS attendance_record (
  record_id          TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  institution_id     TEXT NOT NULL REFERENCES institution(id),
  session_id         TEXT NOT NULL REFERENCES attendance_session(session_id) ON DELETE CASCADE,
  student_id         TEXT NOT NULL REFERENCES student(student_id),
  status             TEXT NOT NULL DEFAULT 'ABSENT'
                     CHECK(status IN (
                       'PRESENT','ABSENT','LATE','EXCUSED','MEDICAL_LEAVE','OFFICIAL_DUTY'
                     )),
  recognition_method TEXT NOT NULL DEFAULT 'SYSTEM_DEFAULT'
                     CHECK(recognition_method IN (
                       'FACE','MANUAL','EXCEPTION','ADMIN_CORRECTION','SYSTEM_DEFAULT'
                     )),
  confidence_score   REAL,             -- NULL for non-face records
  recognized_at      TEXT,             -- NULL until recognized
  manually_corrected INTEGER NOT NULL DEFAULT 0,
  corrected_by       TEXT,
  corrected_at       TEXT,
  correction_reason  TEXT,
  record_state       TEXT NOT NULL DEFAULT 'ACTIVE'
                     CHECK(record_state IN ('ACTIVE','VOIDED')),
  version            INTEGER NOT NULL DEFAULT 1,
  created_at         TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at         TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(session_id, student_id)  -- Enforces Option A: one record per student per session
);

CREATE INDEX IF NOT EXISTS idx_record_session
  ON attendance_record(session_id, status, record_state);

CREATE INDEX IF NOT EXISTS idx_record_student
  ON attendance_record(student_id, status, record_state);

CREATE INDEX IF NOT EXISTS idx_record_attendance_pct
  ON attendance_record(student_id, session_id, status, record_state);
